name: Python package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.11
        with:
          poetry_version: "==1.2.0b2"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          extra_build_dependency_packages: "liblapack-dev gfortran"
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
          plugins: "poetry-dynamic-versioning-plugin"